[package]
name = "structmap"
version = "0.1.0"
authors = ["ex0dus-0x <ex0dus@codemuch.tech>"]
edition = "2018"

[dependencies]
structmap-derive = { path = "structmap-derive", version = "0.1.0" }

[workspace]
